version: '3.3'

services:
  cesp-nginx: 
    image: cr.yandex/crpokl1ir0egpga1r9a7/cesp-nginx
    container_name: cesp-nginx
    restart: always
    ports: 
      - 80:80
      - 443:443
    links:
      - cesp-frontend
      - cesp-service
  
  cesp-frontend:
    image: cr.yandex/crpokl1ir0egpga1r9a7/cesp-frontend:latest
    container_name: cesp-frontend
    restart: always
    
  cesp-service:
    image: cr.yandex/crpokl1ir0egpga1r9a7/cesp-service:latest
    container_name: cesp-service
    depends_on:
      - cesp-service-db
    restart: always
    volumes:
      - resources_data:/app/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
        
  cesp-service-db:
    image: postgres:latest
    container_name: cesp-service-db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: cesp-user
      POSTGRES_DB: cesp-database
      POSTGRES_PASSWORD: mSxqFn4x
volumes:
  postgres_data: {}
  resources_data: {}